### ISSUE TITLE
Optimize log out button is visible in the UI

### ISSUE THREAD

**Issue by RomanJRW** [camunda/camunda-platform-helm#2572] opened 2024-11-15 15:06 UTC
**Describe the issue:**

Optimize SM does not support logging out with Identity. However, the button is visible in the UI, leading to confusing behaviour for the customer

Hint: Optimize has the following config option which allows the log out button to be hidden:

```
ui:
  # If you have SSO enabled, you can set the property below to hide the logout option if it is not needed
  logoutHidden: ${CAMUNDA_OPTIMIZE_UI_LOGOUT_HIDDEN:false}
```

Origin: https://jira.camunda.com/browse/SUPPORT-22732

**Actual behavior:**

The log out button is visible but does not work properly

**Expected behavior:**

The log out button should be hidden

**How to reproduce:**

**Logs:**

**Environment:**

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: 
- Helm CLI version: 
- Chart version: 
- Values file:

**Comment by aabouzaid** [comment] 2024-11-15 15:17
Looking at this [issue](https://github.com/camunda/camunda-platform-helm/issues/570), and found no history for it, it could have been removed by mistake.

I will add it to the 8.7 release cycle :+1:

**Comment by alexcorremans** [comment] 2024-11-15 15:46
Since this is a bug, is there a reason why we're not including it in an earlier patch release?

**Comment by aabouzaid** [comment] 2024-11-15 23:35
> Since this is a bug, is there a reason why we're not including it in an earlier patch release?

@alexcorremans has no capacity for it, and it has too low impact.

Also, I'm unsure if it's a real issue, as I see the logout button in the latest stable version, 8.6, and the latest alpha version, 8.7 alpha1.

I still need to check 8.5, but maybe the user just doesn't see it.

**Comment by aabouzaid** [comment] 2024-11-19 13:27
@RomanJRW, I confirm the logout button is visible in the UI and works as expected back to 8.5.8 (it shows on the user icon).

Feel free to close this issue if that's the case.

![optimize-8 5-8-logout](https://github.com/user-attachments/assets/cedc6a2a-f7ba-4c17-b6e7-60968ef3f27e)

**Comment by aabouzaid** [comment] 2024-11-19 13:44
@alexcorremans I can confirm it works for me on Camunda `8.5.8` and Firefox `125.0.2`.
We need some steps to reproduce it.

**Comment by aabouzaid** [comment] 2024-12-02 20:20
After discussing with @RomanJRW, I'm closing this issue for now as it looks false positive.
We could open it again when we have more evidence about it.

**Closed by aabouzaid** 2024-12-02 20:20 UTC
Labels: platform/aws, kind/issue, size/xs, platform/gcp, support, cycle/pre-release
