### ISSUE TITLE
port forwarding in kubernets 

### ISSUE THREAD

**Issue by Korlapati123** [camunda/camunda-platform-helm#2391] opened 2024-10-01 07:22 UTC
**Describe the issue:**

i unable port forwarding kubernets all deployment and pod are running. i try execute port forwarding command it takes so much time put not working please help the task. please help for the open console.

```[tasklist]
### Tasks
```

**Comment by aabouzaid** [comment] 2024-10-07 14:31
@Korlapati123 Could you please add steps to reproduce this issue?
Also add the details about the chart version, Helm CLI version, and deployment environment.

**Comment by Korlapati123** [comment] 2024-10-08 05:10
Hi,

Helm version version.BuildInfo{Version:"v3.16.1", GitCommit:"5a5449dc42be07001fd5771d56429132984ab3ab", GitTreeState:"clean", GoVersion:"go1.22.7"}

chart version camunda-platform-10.4.0
![Screenshot from 2024-10-08 10-37-34](https://github.com/user-attachments/assets/779cd42b-9de9-4c27-b4f8-26aa7bb88fb3)

please help for ingress deploy camunda bpm pods are not running still pending mode.


Thanks,
korlapati mohan krishna.

**Comment by aabouzaid** [comment] 2024-11-01 13:52
@Korlapati123 Please check the [Ingress guide](https://docs.camunda.io/docs/8.5/self-managed/setup/guides/ingress-setup/).
Given that's not a bug, I'm closing this issue.

**Closed by aabouzaid** 2024-11-01 13:52 UTC
Labels: kind/issue
