### ISSUE TITLE
[ISSUE] Connect to an OpenID Connect provider breaks operate/tasklist communication with zeebe

### ISSUE THREAD

**Issue by alexmeise** [camunda/camunda-platform-helm#1366] opened 2024-02-26 14:31 UTC
**Describe the issue:**

I was trying to "Connect to an OpenID Connect provider" as described in this instructions:

https://docs.camunda.io/docs/self-managed/platform-deployment/helm-kubernetes/guides/connect-to-an-oidc-provider/?optionsType=helm#steps

Withouth success. Error: 

`"Failed to parse authorization request: No response_type provided"` issue shows up on the OIDC provider and the same in OPERATE and TASKLIST when enabling DEBUG log level (see below).

**Actual behavior:**

Neither operate or tasklist are able to download partitions from zeebe. 

`Error occurred when requesting partition ids from Zeebe client: null. `

see more logs below

**Expected behavior:**

I would expect no errors in the communication between operate (or tasklist) and zeebe.
I would expect the response_type to be set. 
I would expect auth to just work after configuring it how the instructions suggest to do it.
I would expect more detailed documentation and clarifications what enabling global: auth type generic means, how to configure it, what configurations are crucial, what scopes, how does the process work, etc, for example: 

When enabling auth: is it only cointainer to container communication or also client authentication against the different components website? 
How does a succesful setup look like and how to troubleshoot a non succesful setup. 

And so on. 

**How to reproduce:**

    global: {
      identity: {
        auth: {
          enabled: true,
          issuer: 'https://myoidc.com',  // It's supposed to be just a name
          issuerBackendUrl: 'https://myoidc.com/auth/',  // validate the JWT tokens in a container to container context.
          tokenUrl: 'https://myoidc.com/auth',  // to request JWT tokens.
          jwksUrl: 'https://myoidc.com/keys',  // JWKS stands for JSON Web KEYS, to validate JWT tokens.
          type: 'GENERIC',
          operate: {
            clientId: 'operate',
            audience: 'operate-api',
            existingSecret: 'secret',
            redirectUrl: 'https://operate.mydomain.com/identity-callback',
          },
          tasklist: {
            clientId: 'tasklist',
            audience: 'tasklist-api',
            existingSecret: 'secret',
            redirectUrl: 'http://tasklist.mydomain.com/identity-callback',
          },
          zeebe: {
            clientId: 'zeebe',
            audience: 'zeebe-api',
            existingSecret: 'secret',
            tokenScope: 'openid', 
          },
        ...
        },
      },
    },
    identity: {
      enabled: false,
    },

The rest are just the defaults, only operate, tasklist and zeebe broker enabled, rest is disabled. ES enabled as well. 

**Logs:**

```
operate 2024-02-26 13:52:26.669  WARN 7 --- [main] i.c.z.c.i.ZeebeCallCredentials: The request's security level does not guarantee that the credentials will be confidential.
operate 2024-02-26 13:52:26.676 DEBUG 7 --- [ault-executor-0] s.n.w.p.h.HttpURLConnection: sun.net.www.MessageHeader@20b416377 pairs: {POST /auth/HTTP/1.1: null}{Content-Type: application/x-www-form-urlencoded}{Accept: application/json}{User-Agent: zeebe-client-java/8.4.3}{Host: MYOIDCPROVIDER.com}{Connection: keep-alive}{Content-Length: 116}
operate 2024-02-26 13:52:26.684 DEBUG 7 --- [ault-executor-0] s.n.w.p.h.HttpURLConnection: sun.net.www.MessageHeader@135f4c006 pairs: {null: HTTP/1.1 303 See Other}{Date: Mon, 26 Feb 2024 13:52:26 GMT}{Content-Length: 0}{Connection: keep-alive}{Location: /auth/?error=invalid_request&error_description=No+response_type+provided&state=}{Strict-Transport-Security: max-age=15724800; includeSubDomains}
operate 2024-02-26 13:52:26.704  WARN 7 --- [main] i.c.o.z.PartitionHolder: Error occurred when requesting partition ids from Zeebe client: null
```

**Environment:**

Kubernetes
No special network policies or restrictions that could affect. 
Enabling auth on a working setup turns the setup down. 
removing global:identity:auth recovers the system and everything works again. 

**Please note: Without the following info, it's hard to resolve the issue and probably it will be closed.**

- Platform: Kubernetes on VMs
- Helm CLI version: Latest
- Chart version: 9.1.2
- Values file: specified previosly on the post.

**Comment by alexmeise** [comment] 2024-03-19 14:21
Does global.identity.auth.enabled:true need identity.enabled: true? Can you have OIDC generic auth withouth identity?

**Comment by alexmeise** [comment] 2024-03-20 10:03
This is what I get in identity (fullURL is set to ingress URL). The rest is the defaults from helm chart. 

```
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.9)

2024-03-20 09:56:59.611  INFO 1 --- [           main] i.c.i.Application                        : Starting Application using Java 17.0.10 with PID 1 (/app/identity.jar started by ? in /app)
2024-03-20 09:56:59.621  INFO 1 --- [           main] i.c.i.Application                        : The following 1 profile is active: "oidc"
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
2024-03-20 09:57:02.426  WARN 1 --- [           main] ocalVariableTableParameterNameDiscoverer : Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: io.camunda.identity.security.spring.filter.FilterExceptionHandler
2024-03-20 09:57:02.702  WARN 1 --- [           main] ocalVariableTableParameterNameDiscoverer : Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: io.camunda.identity.config.IdentityCommon
2024-03-20 09:57:02.833  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'groupController' defined in URL [jar:file:/app/
a/identity/controller/GroupController.class]: Unsatisfied dependency expressed through constructor parameter 0: No qualifying bean of type 'io.camunda.identity.service.GroupService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2024-03-20 09:57:02.905 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in io.camunda.identity.controller.GroupController required a bean of type 'io.camunda.identity.service.GroupService' that could not be found.


Action:

Consider defining a bean of type 'io.camunda.identity.service.GroupService' in your configuration.

```

**Comment by aabouzaid** [comment] 2024-03-26 03:42
@alexmeise please try the latest chart version [camunda-platform-9.3.2](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-9.3.2).

**Comment by mmack** [comment] 2024-03-26 07:55
@aabouzaid i have the same error with the helm chart version 9.3.2 and operate 8.3.4. But only operate. Not optimize or others..

**Comment by alexmeise** [comment] 2024-03-27 15:03
> @alexmeise please try the latest chart version [camunda-platform-9.3.2](https://github.com/camunda/camunda-platform-helm/releases/tag/camunda-platform-9.3.2).

I did already the day the release came out but no changes. I had to adapt my code by adding "fullURL" but the issue isnt solve yet. I would be thankful if the documentation on "Bring your own OIDC" could be extended with a bit more detail as I havent been able to make it work.

**Comment by jessesimpson36** [comment] 2024-04-08 14:25
Possibly related : https://github.com/camunda/camunda-platform-helm/issues/1442

We think this issue might be fixed on main, but not yet released yet.

**Comment by mmack** [comment] 2024-04-10 17:03
I can confirm: Helm Chart 9.3.3 works for me.

**Closed** 2024-04-24 11:03 UTC
Labels: kind/issue
