### ISSUE TITLE
Number of replicas is hardcoded in some components

### ISSUE THREAD

**Issue by rkosegi** [camunda/camunda-platform-helm#1038] opened 2023-11-06 07:43 UTC
We run camunda-platform in our clusters for some time. While doing production readiness review, I noticed that few components can't be scaled to more replicas then 1, since this value is hard-coded in chart, for example operate: 

https://github.com/camunda/camunda-platform-helm/blob/a2584a845908e05e982f86e7855b5c98a4f1355b/charts/camunda-platform/templates/operate/deployment.yaml#L11

or identity:

https://github.com/camunda/camunda-platform-helm/blob/a2584a845908e05e982f86e7855b5c98a4f1355b/charts/camunda-platform/charts/identity/templates/deployment.yaml#L8

This posses risk of single point of failure and is flagged by tools as not production ready.

**Comment by aabouzaid** [comment] 2023-11-15 16:56
Hi @rkosegi thanks for reporting this issue.
It's a duplicate of https://github.com/camunda/camunda-platform-helm/issues/975, so I closing it.

**Closed by aabouzaid** 2023-11-15 16:56 UTC

**Comment by Sivajey** [comment] 2024-04-04 12:35
> Hi @rkosegi thanks for reporting this issue. It's a duplicate of https://github.com/camunda/distribution/issues/185, so I closing it.

Hi @aabouzaid , looks like the url is broken, also curious why the replicas are hardcoded for some of the Camunda's components😅

**Comment by aabouzaid** [comment] 2024-04-04 13:47
@Sivajey it's internal repo (it's an epic to support HA).
The replicas are hard-codded because not all components support HA mode (at least not officially out-of-the-box).
